<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>VpnRoute.Phase0.Socks5Logger</RootNamespace>
    <AssemblyName>Socks5Logger</AssemblyName>
  </PropertyGroup>
</Project>
