import { SMOKE_STATE } from "../src/extension/state/smoke-state.js";

export const LARGE_FIXTURE_REVISION = 3999;
export const LARGE_FIXTURE_RULES = 10000;

const ROUTES = ["VPN", "Direct", "Default"];

/**
 * Deterministic ~10000-rule BrowserRoutingStateV1 for browser acceptance of a large inline PAC.
 * Keeps the normal smoke rules, so the same acceptance sites still route the same way.
 */
export function createLargeFixtureState(total = LARGE_FIXTURE_RULES) {
  const rules = SMOKE_STATE.rules.map((rule) => ({ ...rule }));
  for (let i = 0; rules.length < total; i++) {
    rules.push({
      id: "large-" + i,
      name: "Large " + i,
      host: "s" + i + ".z" + (i % 97) + ".large.vpnroute.test",
      matchType: i % 3 === 0 ? "ExactHost" : "DomainAndSubdomains",
      routeMode: ROUTES[Math.floor(i / 3) % ROUTES.length],
      enabled: true,
      source: "User",
      notes: null
    });
  }
  return {
    schemaVersion: 1,
    revision: LARGE_FIXTURE_REVISION,
    defaultRoute: SMOKE_STATE.defaultRoute,
    rules
  };
}

export function renderFixtureModule(name, state) {
  const rules = state.rules.map((rule) => "    " + JSON.stringify(rule)).join(",\n");
  return [
    "// Generated by scripts/build-extension.js (fixture: " + name + "). Dev-only acceptance fixture; do not edit.",
    "",
    "export const FIXTURE_NAME = " + JSON.stringify(name) + ";",
    "",
    "export const SMOKE_STATE = {",
    "  schemaVersion: " + state.schemaVersion + ",",
    "  revision: " + state.revision + ",",
    "  defaultRoute: " + JSON.stringify(state.defaultRoute) + ",",
    "  rules: [",
    rules,
    "  ]",
    "};",
    ""
  ].join("\n");
}
